### PR TITLE
HC-54 Add note that creating a cloud workspaces will add a webhook

### PR DESCRIPTION
**Pull request by vicenter-gitkraken**
https://gitkraken.atlassian.net/browse/HC-54
Add note

### CODE REVIEW

**Comment by Axxzilla** [comment]
I am not sure I understand this one - is this enough information for the end user? 

Adding @jkelroy as a reviewer since it is his Slack thread

**Comment by vicenter-gitkraken** [comment]
> I am not sure I understand this one - is this enough information for the end user?

I asked Jeff and is the message they plan to add to the client. We could add more info like the events in the webhook, but maybe are different depending on the remote.

**Review by jkelroy — APPROVED** [review]
I would agree this is fine, for now. Though as our accept/success message from the page dev is adding will likely be limited, I wonder if we want to expand on _exactly_ what this does from the support site (provided from Jeff/Ashley).

The extended information I have seems to still be a bit generalized and not verbose.
> For insights we track your PR and Issue changes in real time so we can save their rate limits with Bitbucket so we dont have to re-fetch all of their pull requests/issues all over again next time we show them metrics. Which speeds up the experiance when viewing insights metrics

But at the same time, both customers that asked about this were just unsure of if the webhook was intended, which this, and the updated accept/success page, will cover. See this thread: https://gitkraken-hq.slack.com/archives/C026A62471A/p1674249433202659

**Comment by Axxzilla** [comment]
Thanks fellas - merging

**Pull request merged**
