### PR TITLE
New Focus View 

### PR DESCRIPTION
**Pull request by jjsilva4**
DO NOT MERGE

### CODE REVIEW

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://staging.gitkraken.dev/drafts/bd773550-a34e-49dc-8c84-74f2d36d3cd6?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://staging.gitkraken.dev/link/drafts/bd773550-a34e-49dc-8c84-74f2d36d3cd6).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://www.gitkraken.com/solutions/code-suggest) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.com) to speed up PR review._
</details>

**Comment by jjsilva4** [comment]
Hey @jkelroy, pardon the dust but I created this PR to help populate some screenshots. You can close this once the release goes out.

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://staging.gitkraken.dev/drafts/b25154c7-dea3-4bae-ae7a-be9d3fcabbf3?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://staging.gitkraken.dev/link/drafts/b25154c7-dea3-4bae-ae7a-be9d3fcabbf3).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://www.gitkraken.com/solutions/code-suggest) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.com) to speed up PR review._
</details>

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://staging.gitkraken.dev/drafts/63db2817-a874-4435-be01-cececdbdc78a?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://staging.gitkraken.dev/link/drafts/63db2817-a874-4435-be01-cececdbdc78a).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://www.gitkraken.com/solutions/code-suggest) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.com) to speed up PR review._
</details>

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://staging.gitkraken.dev/drafts/08f5cad4-cfc7-4d3e-93eb-9453ca46ff34?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://staging.gitkraken.dev/link/drafts/08f5cad4-cfc7-4d3e-93eb-9453ca46ff34).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://www.gitkraken.com/solutions/code-suggest) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.com) to speed up PR review._
</details>

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://staging.gitkraken.dev/drafts/40137236-2fbb-4a3c-b2ff-5177a363bece?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://staging.gitkraken.dev/link/drafts/40137236-2fbb-4a3c-b2ff-5177a363bece).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://www.gitkraken.com/solutions/code-suggest) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.com) to speed up PR review._
</details>

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Includes missing features**](https://gitkraken.dev/drafts/a2457f84-c4b4-41b5-a11d-a2364d658b4b?source=PRComment)
>Code Suggestion from Joey Kelroy
 to Pull Request #216 made on 05/06/2024

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/a2457f84-c4b4-41b5-a11d-a2364d658b4b).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://www.gitkraken.com/solutions/code-suggest) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.com) to speed up PR review._
</details>

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**example**](https://gitkraken.dev/drafts/7b89756f-2175-44e6-8855-9da13559bd1c?source=PRComment)
>Code Suggestion from Joey Kelroy
 to Pull Request #216 made on 05/06/2024

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/7b89756f-2175-44e6-8855-9da13559bd1c).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://www.gitkraken.com/solutions/code-suggest) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.com) to speed up PR review._
</details>

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Doc updates**](https://gitkraken.dev/drafts/4bcf50ea-7002-4ef9-844e-94a2df804918?source=PRComment)
>Code Suggestion from Joey Kelroy
 to Pull Request #216 made on 05/09/2024

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/4bcf50ea-7002-4ef9-844e-94a2df804918?type=suggested_pr_change&prEntityId=).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://www.gitkraken.com/solutions/code-suggest) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.com) to speed up PR review._
</details>

**Comment by vicenter-gitkraken** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/9617794d-e7bc-40dc-a9bf-83e27d610b8e?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/9617794d-e7bc-40dc-a9bf-83e27d610b8e?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by vicenter-gitkraken** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/a34aad30-0ee5-4b09-8838-7170bafaadcf?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/a34aad30-0ee5-4b09-8838-7170bafaadcf?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by vicenter-gitkraken** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/bcac84a9-0066-4838-8ad8-9c3eb24a85f6?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/bcac84a9-0066-4838-8ad8-9c3eb24a85f6?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by vicenter-gitkraken** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/512e9c81-d936-4d3f-9331-6c35e9198221?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/512e9c81-d936-4d3f-9331-6c35e9198221?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by vicenter-gitkraken** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/6dd0976e-fdc7-4763-a392-1355877dfc0b?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/6dd0976e-fdc7-4763-a392-1355877dfc0b?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/cdf7561a-b2d7-44e9-88a0-3f7c06cc8dff?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/cdf7561a-b2d7-44e9-88a0-3f7c06cc8dff?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by vicenter-gitkraken** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/8b22d6c0-fcc5-43cf-b6bb-67317b8e8e3f?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/8b22d6c0-fcc5-43cf-b6bb-67317b8e8e3f?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by vicenter-gitkraken** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/8e73476a-5402-4abd-9a0a-63f5d1cc1690?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/8e73476a-5402-4abd-9a0a-63f5d1cc1690?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/2b85022a-70c7-4718-80b5-877e1c44f1a5?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/2b85022a-70c7-4718-80b5-877e1c44f1a5?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/b1dab6a4-e2bf-453d-888b-c8c10ba8e9c2?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/b1dab6a4-e2bf-453d-888b-c8c10ba8e9c2?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by jkelroy** [comment]
Hey @jjsilva4, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #216**](https://gitkraken.dev/drafts/3097db22-28fc-4c79-bd7c-05b3122d990f?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/216

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/3097db22-28fc-4c79-bd7c-05b3122d990f?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NXVTbXdPIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Pull request closed without merging**
