### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by jkelroy**
- https://gitkraken.atlassian.net/browse/HC-40
- https://gitkraken.atlassian.net/browse/HC-49
- https://gitkraken.atlassian.net/browse/HC-44

### CODE REVIEW

**Review by Axxzilla — COMMENTED** [review]
Can we double check the requirements for LFS ? We should update to be v6.6.0+ (or maybe v7.0.0, depending on what we will be supporting)

**Comment by jkelroy** [comment]
@Axxzilla are you referring to the Git and LFS requirements or the GKC version requirement? Or both?

If we are only referring to GKC, imo this may not be the best place to put this in, as this is not a specific requirement for LFS. I would imagine we would want to put a general note on a more generic page regarding requiring 6.6/7+ (or put a note on every page? though this seems like overkill).

**Comment by Axxzilla** [comment]
Both. I assume that newer versions of LFS might require a newer version of Git to function. 

for the GKC part - versions prior to 6.6.0 will not be usable or downloadable anymore soon, so we want to make it clear on the LFS requirements page that this is the case.

Separately, yes we will want another section/page for in general only GKC v6.6.0+ is available. That can be done in another PR - I was mentioning it here since you are already updating the page.

**Comment by jkelroy** [comment]
Got input from Alex/Ian in slack confirming the requirements. https://gitkraken-hq.slack.com/archives/C04G42P6V/p1674592282468799

**Review by Axxzilla — APPROVED** [review]

**Pull request merged**
